
DBPrune.services_db_hash = JSON.parse(Figaro.env.services_db_hash)


DBPrune.housing_sms_service_service_name = Figaro.env.housing_sms_service_service_name
DBPrune.housing_sms_service_base_models_for_reflections = Figaro.env.housing_sms_service_base_models_for_reflections
DBPrune.housing_sms_service_master_tables_for_prune = JSON.parse(Figaro.env.housing_sms_service_master_tables_for_prune)
DBPrune.housing_sms_service_base_tables_for_prune = JSON.parse(Figaro.env.housing_sms_service_base_tables_for_prune)
DBPrune.housing_sms_service_has_one_many_reflections_to_read = JSON.parse(Figaro.env.housing_sms_service_has_one_many_reflections_to_read)


